/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthStudentRouteImport } from './routes/_auth/student'
import { Route as AuthOperatorRouteImport } from './routes/_auth/operator'
import { Route as AuthStudentIndexRouteImport } from './routes/_auth/student/index'
import { Route as AuthOperatorIndexRouteImport } from './routes/_auth/operator/index'
import { Route as AuthStudentRequirementsRouteImport } from './routes/_auth/student/requirements'
import { Route as AuthStudentProfileRouteImport } from './routes/_auth/student/profile'
import { Route as AuthStudentApplyRouteImport } from './routes/_auth/student/apply'
import { Route as AuthStudentApplicationsIndexRouteImport } from './routes/_auth/student/applications/index'
import { Route as AuthStudentApplicationsAppIdRouteImport } from './routes/_auth/student/applications.$appId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthStudentRoute = AuthStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOperatorRoute = AuthOperatorRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => AuthRoute,
} as any)
const AuthStudentIndexRoute = AuthStudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthStudentRoute,
} as any)
const AuthOperatorIndexRoute = AuthOperatorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthOperatorRoute,
} as any)
const AuthStudentRequirementsRoute = AuthStudentRequirementsRouteImport.update({
  id: '/requirements',
  path: '/requirements',
  getParentRoute: () => AuthStudentRoute,
} as any)
const AuthStudentProfileRoute = AuthStudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthStudentRoute,
} as any)
const AuthStudentApplyRoute = AuthStudentApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => AuthStudentRoute,
} as any)
const AuthStudentApplicationsIndexRoute =
  AuthStudentApplicationsIndexRouteImport.update({
    id: '/applications/',
    path: '/applications/',
    getParentRoute: () => AuthStudentRoute,
  } as any)
const AuthStudentApplicationsAppIdRoute =
  AuthStudentApplicationsAppIdRouteImport.update({
    id: '/applications/$appId',
    path: '/applications/$appId',
    getParentRoute: () => AuthStudentRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/operator': typeof AuthOperatorRouteWithChildren
  '/student': typeof AuthStudentRouteWithChildren
  '/student/apply': typeof AuthStudentApplyRoute
  '/student/profile': typeof AuthStudentProfileRoute
  '/student/requirements': typeof AuthStudentRequirementsRoute
  '/operator/': typeof AuthOperatorIndexRoute
  '/student/': typeof AuthStudentIndexRoute
  '/student/applications/$appId': typeof AuthStudentApplicationsAppIdRoute
  '/student/applications/': typeof AuthStudentApplicationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/student/apply': typeof AuthStudentApplyRoute
  '/student/profile': typeof AuthStudentProfileRoute
  '/student/requirements': typeof AuthStudentRequirementsRoute
  '/operator': typeof AuthOperatorIndexRoute
  '/student': typeof AuthStudentIndexRoute
  '/student/applications/$appId': typeof AuthStudentApplicationsAppIdRoute
  '/student/applications': typeof AuthStudentApplicationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/operator': typeof AuthOperatorRouteWithChildren
  '/_auth/student': typeof AuthStudentRouteWithChildren
  '/_auth/student/apply': typeof AuthStudentApplyRoute
  '/_auth/student/profile': typeof AuthStudentProfileRoute
  '/_auth/student/requirements': typeof AuthStudentRequirementsRoute
  '/_auth/operator/': typeof AuthOperatorIndexRoute
  '/_auth/student/': typeof AuthStudentIndexRoute
  '/_auth/student/applications/$appId': typeof AuthStudentApplicationsAppIdRoute
  '/_auth/student/applications/': typeof AuthStudentApplicationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/operator'
    | '/student'
    | '/student/apply'
    | '/student/profile'
    | '/student/requirements'
    | '/operator/'
    | '/student/'
    | '/student/applications/$appId'
    | '/student/applications/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/student/apply'
    | '/student/profile'
    | '/student/requirements'
    | '/operator'
    | '/student'
    | '/student/applications/$appId'
    | '/student/applications'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/operator'
    | '/_auth/student'
    | '/_auth/student/apply'
    | '/_auth/student/profile'
    | '/_auth/student/requirements'
    | '/_auth/operator/'
    | '/_auth/student/'
    | '/_auth/student/applications/$appId'
    | '/_auth/student/applications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/student': {
      id: '/_auth/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof AuthStudentRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/operator': {
      id: '/_auth/operator'
      path: '/operator'
      fullPath: '/operator'
      preLoaderRoute: typeof AuthOperatorRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/student/': {
      id: '/_auth/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof AuthStudentIndexRouteImport
      parentRoute: typeof AuthStudentRoute
    }
    '/_auth/operator/': {
      id: '/_auth/operator/'
      path: '/'
      fullPath: '/operator/'
      preLoaderRoute: typeof AuthOperatorIndexRouteImport
      parentRoute: typeof AuthOperatorRoute
    }
    '/_auth/student/requirements': {
      id: '/_auth/student/requirements'
      path: '/requirements'
      fullPath: '/student/requirements'
      preLoaderRoute: typeof AuthStudentRequirementsRouteImport
      parentRoute: typeof AuthStudentRoute
    }
    '/_auth/student/profile': {
      id: '/_auth/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof AuthStudentProfileRouteImport
      parentRoute: typeof AuthStudentRoute
    }
    '/_auth/student/apply': {
      id: '/_auth/student/apply'
      path: '/apply'
      fullPath: '/student/apply'
      preLoaderRoute: typeof AuthStudentApplyRouteImport
      parentRoute: typeof AuthStudentRoute
    }
    '/_auth/student/applications/': {
      id: '/_auth/student/applications/'
      path: '/applications'
      fullPath: '/student/applications/'
      preLoaderRoute: typeof AuthStudentApplicationsIndexRouteImport
      parentRoute: typeof AuthStudentRoute
    }
    '/_auth/student/applications/$appId': {
      id: '/_auth/student/applications/$appId'
      path: '/applications/$appId'
      fullPath: '/student/applications/$appId'
      preLoaderRoute: typeof AuthStudentApplicationsAppIdRouteImport
      parentRoute: typeof AuthStudentRoute
    }
  }
}

interface AuthOperatorRouteChildren {
  AuthOperatorIndexRoute: typeof AuthOperatorIndexRoute
}

const AuthOperatorRouteChildren: AuthOperatorRouteChildren = {
  AuthOperatorIndexRoute: AuthOperatorIndexRoute,
}

const AuthOperatorRouteWithChildren = AuthOperatorRoute._addFileChildren(
  AuthOperatorRouteChildren,
)

interface AuthStudentRouteChildren {
  AuthStudentApplyRoute: typeof AuthStudentApplyRoute
  AuthStudentProfileRoute: typeof AuthStudentProfileRoute
  AuthStudentRequirementsRoute: typeof AuthStudentRequirementsRoute
  AuthStudentIndexRoute: typeof AuthStudentIndexRoute
  AuthStudentApplicationsAppIdRoute: typeof AuthStudentApplicationsAppIdRoute
  AuthStudentApplicationsIndexRoute: typeof AuthStudentApplicationsIndexRoute
}

const AuthStudentRouteChildren: AuthStudentRouteChildren = {
  AuthStudentApplyRoute: AuthStudentApplyRoute,
  AuthStudentProfileRoute: AuthStudentProfileRoute,
  AuthStudentRequirementsRoute: AuthStudentRequirementsRoute,
  AuthStudentIndexRoute: AuthStudentIndexRoute,
  AuthStudentApplicationsAppIdRoute: AuthStudentApplicationsAppIdRoute,
  AuthStudentApplicationsIndexRoute: AuthStudentApplicationsIndexRoute,
}

const AuthStudentRouteWithChildren = AuthStudentRoute._addFileChildren(
  AuthStudentRouteChildren,
)

interface AuthRouteChildren {
  AuthOperatorRoute: typeof AuthOperatorRouteWithChildren
  AuthStudentRoute: typeof AuthStudentRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthOperatorRoute: AuthOperatorRouteWithChildren,
  AuthStudentRoute: AuthStudentRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
