/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthStudentRouteImport } from './routes/_auth/student'
import { Route as AuthOperatorRouteImport } from './routes/_auth/operator'
import { Route as AuthStudentIndexRouteImport } from './routes/_auth/student/index'
import { Route as AuthOperatorIndexRouteImport } from './routes/_auth/operator/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthStudentRoute = AuthStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOperatorRoute = AuthOperatorRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => AuthRoute,
} as any)
const AuthStudentIndexRoute = AuthStudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthStudentRoute,
} as any)
const AuthOperatorIndexRoute = AuthOperatorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthOperatorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/operator': typeof AuthOperatorRouteWithChildren
  '/student': typeof AuthStudentRouteWithChildren
  '/operator/': typeof AuthOperatorIndexRoute
  '/student/': typeof AuthStudentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/operator': typeof AuthOperatorIndexRoute
  '/student': typeof AuthStudentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/operator': typeof AuthOperatorRouteWithChildren
  '/_auth/student': typeof AuthStudentRouteWithChildren
  '/_auth/operator/': typeof AuthOperatorIndexRoute
  '/_auth/student/': typeof AuthStudentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/operator'
    | '/student'
    | '/operator/'
    | '/student/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/operator' | '/student'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/operator'
    | '/_auth/student'
    | '/_auth/operator/'
    | '/_auth/student/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/student': {
      id: '/_auth/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof AuthStudentRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/operator': {
      id: '/_auth/operator'
      path: '/operator'
      fullPath: '/operator'
      preLoaderRoute: typeof AuthOperatorRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/student/': {
      id: '/_auth/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof AuthStudentIndexRouteImport
      parentRoute: typeof AuthStudentRoute
    }
    '/_auth/operator/': {
      id: '/_auth/operator/'
      path: '/'
      fullPath: '/operator/'
      preLoaderRoute: typeof AuthOperatorIndexRouteImport
      parentRoute: typeof AuthOperatorRoute
    }
  }
}

interface AuthOperatorRouteChildren {
  AuthOperatorIndexRoute: typeof AuthOperatorIndexRoute
}

const AuthOperatorRouteChildren: AuthOperatorRouteChildren = {
  AuthOperatorIndexRoute: AuthOperatorIndexRoute,
}

const AuthOperatorRouteWithChildren = AuthOperatorRoute._addFileChildren(
  AuthOperatorRouteChildren,
)

interface AuthStudentRouteChildren {
  AuthStudentIndexRoute: typeof AuthStudentIndexRoute
}

const AuthStudentRouteChildren: AuthStudentRouteChildren = {
  AuthStudentIndexRoute: AuthStudentIndexRoute,
}

const AuthStudentRouteWithChildren = AuthStudentRoute._addFileChildren(
  AuthStudentRouteChildren,
)

interface AuthRouteChildren {
  AuthOperatorRoute: typeof AuthOperatorRouteWithChildren
  AuthStudentRoute: typeof AuthStudentRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthOperatorRoute: AuthOperatorRouteWithChildren,
  AuthStudentRoute: AuthStudentRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
